import type { Metadata } from "next";
import "./globals.css";
import MainNav from "./_components/MainNav";
import { getSession } from "./_auth/auth";
import SignIn from "./_auth/SignIn";
import Providers from "./_context/Providers";
import Notifications from "./nfts/Notifications";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="en" data-theme="dracula">
      <body>
        <Providers>
          {!session ? (
            <SignIn />
          ) : (
            <>
              <MainNav username={session.user.user_name} />
              <main className="min-h-svh p-12 flex justify-center bg-neutral">
                <div className="max-w-7xl pt-16 w-full">{children}</div>
              </main>
              <Notifications />
            </>
          )}
        </Providers>
      </body>
    </html>
  );
}
